name: Post National Investigative News
on:
  schedule:
    - cron: '37 1 * * *'
    - cron: '14 5 * * *'
    - cron: '52 9 * * *'
    - cron: '28 13 * * *'
    - cron: '09 17 * * *'
    - cron: '44 21 * * *'
  workflow_dispatch:
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python news_bot.py
        env:
          BB_URL2: ${{ secrets.BB_URL2 }}
          BB_USER2: ${{ secrets.BB_USER2 }}
          BB_PASS2: ${{ secrets.BB_PASS2 }}
